app/entity/ml/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from flask_login import current_user
from wtforms import StringField,PasswordField,SubmitField,BooleanField #, TextAreaField
from wtforms.validators import DataRequired,length,Email,EqualTo,ValidationError
from app.Models import User




class RegistrationForm(FlaskForm):
    username =StringField('UserName',
                                validators=[DataRequired(),length(min=4 ,max=20)])
    email =StringField('Email',
                           validators=[DataRequired(),Email()])
    password =PasswordField('Password',
                                  validators=[DataRequired(),length(min=8 ,max=20)])
    confirm_password =PasswordField('ConfirmPassword',
                                  validators=[DataRequired(),EqualTo('password')])
    submit = SubmitField('Sign up')
    
    def validate_username(self,username):
        user = User.query.filter_by(username=username.data).first()

        if user:
            raise ValidationError('This username is taken.Please choose a different name')

    def validate_email(self,email):
        email = User.query.filter_by(email=email.data).first()

        if email:
            raise ValidationError('This email is already used by  another user')

class LoginForm(FlaskForm):
    username =StringField('UserName',
                                     validators=[DataRequired(),length(min=4 ,max=20)] )
    email =StringField('Email',
                            validators=[DataRequired(),Email()])
    password =PasswordField('Password',
                                  validators=[DataRequired(),length(min=4 ,max=20)])
    remember = BooleanField('Remember me')                              
    submit = SubmitField('Login')

app/entity/extra/routes.py
from flask import render_template, url_for,flash,redirect,request,abort,Blueprint
from app.Models import subject,Classes,Student,Term,classyear,Year,reportcard,reportdata
from app.entity.extra.forms import CreateForm,SubjectForm,ClassForm,YearForm,StudentForm,reportForm
from app import bcrypt,db
from sqlalchemy import or_, and_, distinct, func
from app.entity.ml.utils import machine_learning






extra =Blueprint('extra',__name__)

@extra.route('/viewsubject')
def viewsubject():
    des=subject.query.all()
    return render_template('fabien-ui/viewsub.html',legend="login",des=des)

@extra.route('/insertsubject',methods=['GET','POST'])
def subjects():
    form=SubjectForm()
    if form.validate_on_submit():
        buses=subject(name=form.name.data,coefficient=form.coefficient.data,Type=form.science.data)
        db.session.add(buses)
        db.session.commit()
        return redirect(url_for('extra.viewsubject'))
    return render_template('fabien-ui/add_sub.html',legend="login",form=form)

@extra.route('/studentyears/<id>')
def studentyears(id):
    des=classyear.query.filter_by(student_id=id).all()
    return render_template('fabien-ui/stud_yr.html',legend="login",des=des,id=id)

@extra.route('/studentterms/<id>/<stud>')
def studentterms(id,stud):
    des=reportcard.query.filter(and_(reportcard.year_id==id,reportcard.student_id==stud)).all()
    return render_template('fabien-ui/stuterms.html',legend="login",des=des,id=id,stud=stud)

@extra.route('/repodata/<id>')
def repodata(id):
    des=reportdata.query.filter_by(reportcard=id).all()
    return render_template('fabien-ui/repoda.html',legend="login",des=des,id=id)

@extra.route('/classyear/<id>')#all class for that year
def viewclassyear(id):
    des=classyear.query.filter_by(year_id=id).all()
    return render_template('fabien-ui/classenro.html',legend="login",des=des)


@extra.route('/insertclassyear',methods=['GET','POST'])
def insertclassyear():
    form=ClassForm()
    terms=Term.query.all()
    if form.validate_on_submit():
        buses=classyear(class_id=form.class_id.data,year_id=form.year_id.data,student_id=form.student_id.data)
        db.session.add(buses)
        db.session.commit()
        for i in terms:
            student_card=reportcard(Term=i.id,student_id=buses.student_id,year_id=buses.year_id)
            db.session.add(student_card)
            db.session.commit()
        return redirect(url_for('extra.viewclassyear',id=buses.year_id))
    return render_template('fabien-ui/add_c_s.html',legend="login",form=form)



@extra.route('/viewclass')
def viewclass():
    des=Classes.query.all()
    return render_template('fabien-ui/viewclass.html',legend="login",des=des)

@extra.route('/insertclass',methods=['GET','POST'])
def classes():
    form=CreateForm()
    if form.validate_on_submit():
        buses=Classes(name=form.name.data)
        db.session.add(buses)
        db.session.commit()
        return redirect(url_for('extra.viewclass'))
    return render_template('fabien-ui/add_class.html',legend="login",form=form)

@extra.route('/viewstudents')
def viewstudents():
    des=Student.query.all()
    return render_template('fabien-ui/view_stud.html',legend="login",des=des)

@extra.route('/insertstudents',methods=['GET','POST'])
def students():
    form=StudentForm()
    if form.validate_on_submit():
        time=form.enrollement.data#put date here
        buses=Student(name=form.name.data,enrollement=time)
        db.session.add(buses)
        db.session.commit()
        return redirect(url_for('extra.viewstudents'))
    return render_template('fabien-ui/add_student.html',legend="login",form=form)

@extra.route('/viewterms')
def viewterms():
    des=Term.query.all()
    return render_template('fabien-ui/viewterm.html',legend="login",des=des)

@extra.route('/insertterms',methods=['GET','POST'])
def terms():
    form=CreateForm()
    if form.validate_on_submit():
        buses=Term(name=form.name.data)
        db.session.add(buses)
        db.session.commit()
        return redirect(url_for('extra.viewterms'))
    return render_template('fabien-ui/add_term.html',legend="login",form=form)


@extra.route('/viewyears')
def viewyears():
    des=Year.query.all()
    return render_template('fabien-ui/allyears.html',legend="login",yrs=des)

@extra.route('/insertyears',methods=['GET','POST'])
def years():
    form=YearForm()
    if form.validate_on_submit():
        buses=Year(name=form.Year.data)
        db.session.add(buses)
        db.session.commit()
        return redirect(url_for('users.dashboard'))
    return render_template('fabien-ui/add_year.html',legend="login",form=form)


@extra.route('/reportdat/<id>',methods=['GET','POST'])
def reportdat(id):
    form=reportForm()
    if form.validate_on_submit():
        buses=reportdata(reportcard=id,subject_id=form.subject.data,mark=form.mark.data)
        db.session.add(buses)
        db.session.commit()
        if buses.mark >= 15 and buses.mark < 18: 
            buses.grade='B'
        if buses.mark >= 18 : 
            buses.grade='A'
        if buses.mark < 15 : 
            buses.grade='C'
        if buses.mark < 10 : 
            buses.grade='D'
        db.session.commit()
        
        return redirect(url_for('extra.repodata',id=id))
    return render_template('fabien-ui/add_report.html',legend="login",form=form)


@extra.route('/machinelearning/<id>/<stud>')#all class for that year
def machine(id,stud):
    des=reportcard.query.filter(and_(reportcard.year_id==id,reportcard.student_id==stud)).all()
    rep=machine_learning(des) 
    return render_template('fabien-ui/ml.html',rep=rep)

app/entity/ml/routes.py
from flask import render_template, url_for,flash,redirect,request,abort,Blueprint







ml =Blueprint('ml',__name__)

app/entity/report/routes.py
from flask import render_template, url_for,flash,redirect,request,abort,Blueprint







report =Blueprint('report',__name__)



@report.route('/insertreport')
def reportcard():
    form=reportForm()
    if form.validate_on_submit():
        term=form.term.data#run queries
        student=form.student.data
        subject=form.subject.data
        mark=form.mark.data
        grade=form.grade.data
        year=form.year.data
        classz=form.classz.data
        report_card=form#get you some report data
        buses=reportdata(reportcard=reportcard.id,subject_id=subject.id,mark=mark,grade=grade)
        db.session.add(buses)
        db.session.commit()
        return redirect(url_for('users.dashboard'))
    return render_template('fabien-ui/location.html',legend="login",form=form)

app/entity/users/routes.py
from flask import render_template, url_for,flash,redirect,request,abort,Blueprint
from flask_login import login_user,current_user,logout_user,login_required
from app.entity.users.forms import LoginForm,RegistrationForm
from app.Models import User,Term,Student,Classes,reportcard,Year,subject
from app import bcrypt,db
from datetime import date,timedelta,datetime,timezone 





users =Blueprint('users',__name__)

@users.route('/login',methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        if current_user.Type=='Admin':
            return redirect(url_for('users.dashboard'))
    form = LoginForm()
    if form.validate_on_submit():
        name=User.query.filter_by(username=form.username.data).first()#put login
        if  name and bcrypt.check_password_hash(name.password,form.password.data):
            login_user(name,remember=form.remember.data,duration=timedelta(seconds=30)) 
            next_page=request.args.get('next') 
            return redirect (next_page) if next_page else  redirect(url_for('users.dashboard'))
        else:
    
            flash(f'Mauvais Identifiant ou mot de passe, essayez à nouveau','danger')

    return render_template('fabien-ui/login.html',legend="login",form=form)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('users.login'))



@users.route('/sign_up',methods=['GET','POST'])
def sign_up():
    if current_user.is_authenticated:
       return redirect(url_for('users.dashboard'))
    form = RegistrationForm()

    if form.validate_on_submit():#check user 
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user=User(username=form.username.data,email=form.email.data,Type=form.type.data,password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Account created you can now login','success')
        return redirect(url_for('users.login'))
    return render_template('fabien-ui/register.html',legend="sign_up",form=form)


@users.route('/dashboard',methods=['GET','POST'])
def dashboard():
    terms=subject.query.count()
    students=Student.query.count()
    classes=Classes.query.count()
    report=reportcard.query.count()
    year=Year.query.count()
    return render_template('fabien-ui/index.html',classes=classes,term=terms,students=students,reportcard=report,year=year)

app/templates/fabien-ui/login.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>AdminLTE 3 | Log in</title>

<!-- Google Font: Source Sans Pro -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&amp;display=fallback">
<!-- Font Awesome -->
<link rel="stylesheet" href="{{url_for('static', filename='plugins/fontawesome-free/css/all.min.css')}}">
<!-- icheck bootstrap -->
<link rel="stylesheet" href="{{url_for('static', filename='plugins/icheck-bootstrap/icheck-bootstrap.min.css')}}">
<!-- Theme style -->
<link rel="stylesheet" href="{{url_for('static', filename='dist/css/adminlte.min.css')}}">
</head>
  <body class="login-page" style="min-height: 496.8px;">
  <div class="login-box">
    <div class="login-logo">
      <a href="../../index2.html"><b>SMS</b></a>
    </div>
    <!-- /.login-logo -->
    <div class="card">
      <div class="card-body login-card-body">
        <p class="login-box-msg">Sign in to start your session</p>

        <form  method="POST">
          {{ form.hidden_tag() }}
          <div class="input-group mb-3">
           
            {% if form.username.errors %}
            <div class="invalid-feedback">
                {% for error in form.username.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{form.username(class="form-control",placeholder="username")}}
            {% endif %}
            <div class="input-group-append">
              <div class="input-group-text">
                <span class="fas fa-envelope"></span>
              </div>
            </div>
          </div>
          <div class="input-group mb-3">

            {% if form.password.errors %}
            <div class="invalid-feedback">
                {% for error in form.password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{form.password(class="form-control",placeholder="password")}}
            {% endif %}
            <div class="input-group-append">
              <div class="input-group-text">
                <span class="fas fa-lock"></span>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-8">
              <div class="icheck-primary">
                {{form.remember()}}
                {{form.remember.label()}}
              </div>
            </div>
            <!-- /.col -->
            <div class="col-4">
              {{form.submit(class="btn btn-primary btn-block")}}
            </div>
            <!-- /.col -->
          </div>
        </form>

        <div class="social-auth-links text-center mb-3">
          <p>- OR -</p>
          <a href="#" class="btn btn-block btn-danger">
            <i class="fab fa-google-plus mr-2"></i> Sign in using Google+
          </a>
        </div>
        <!-- /.social-auth-links -->

        <p class="mb-1">
          <a href="forgot-password.html">I forgot my password</a>
        </p>
        <p class="mb-0">
          <a href="{{url_for('users.sign_up')}}" class="text-center">Register a new membership</a>
        </p>
      </div>
      <!-- /.login-card-body -->
    </div>
  </div>
  <!-- /.login-box -->

  <!-- jQuery -->
  <script src="{{url_for('static', filename='plugins/jquery/jquery.min.js')}}"></script>
  <!-- Bootstrap 4 -->
  <script src="{{url_for('static', filename='plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
  <!-- AdminLTE App -->
  <script src="{{url_for('static', filename='dist/js/adminlte.min.js')}}"></script>


  </body>
</html>

app/templates/fabien-ui/stud_yr.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AdminLTE 3 | Dashboard</title>
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{url_for('static', filename='plugins/fontawesome-free/css/all.min.css')}}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="{{url_for('static', filename='plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css')}}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{{url_for('static', filename='plugins/icheck-bootstrap/icheck-bootstrap.min.css')}}">
    <!-- JQVMap -->
    <link rel="stylesheet" href="{{url_for('static', filename='plugins/jqvmap/jqvmap.min.css')}}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{url_for('static', filename='dist/css/adminlte.min.css')}}">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{{url_for('static', filename='plugins/overlayScrollbars/css/OverlayScrollbars.min.css')}}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{{url_for('static', filename='plugins/daterangepicker/daterangepicker.css')}}">
    <!-- summernote -->
    <link rel="stylesheet" href="{{url_for('static', filename='plugins/summernote/summernote-bs4.min.css')}}">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  <!-- Preloader
  <div class="preloader flex-column justify-content-center align-items-center">
    <img class="animation__shake" src="dist/img/AdminLTELogo.png" alt="AdminLTELogo" height="60" width="60">
  </div>
 -->
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('users.logout')}}"  role="button">
          Deconnexion
        </a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link text-center">
      <span class="brand-text font-weight-light">AdminLTE 3</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          
        </div>
        <div class="info">
          <a href="#" class="d-block"></a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
            <li class="nav-item">
            <a href="{{url_for('users.dashboard')}}" class="nav-link">
              <p>
                Dashboard
              </p>
            </a>
          </li>

          {% if current_user%}
          <li class="nav-item">
            <a href="{{url_for('extra.students')}}" class="nav-link">
              <i class="nav-icon text-info"></i>
              <p>Create Student</p>
            </a>
          </li>
          {%endif%}

          <li class="nav-item">
            <a href="{{url_for('users.dashboard')}}" class="nav-link">
              <i class="nav-icon text-info"></i>
              <p>Profile</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{url_for('report.reportcard')}}" class="nav-link">
              <i class="nav-icon text-info"></i>
              <p>Create reportcard</p>
            </a>
          </li>
          {% if current_user%}
          <li class="nav-item">
            <a href="{{url_for('extra.classes')}}" class="nav-link">
              <i class="nav-icon text-info"></i>
              <p>Create classes</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{url_for('extra.years')}}" class="nav-link">
              <i class="nav-icon text-info"></i>
              <p>Add year</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{url_for('extra.insertclassyear')}}" class="nav-link">
              <i class="nav-icon text-info"></i>
              <p>Add Student-Class</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{url_for('extra.terms')}}" class="nav-link">
              <i class="nav-icon text-info"></i>
              <p>Add terms</p>
            </a>
          </li>
          {% endif %}

        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Years</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a class="btn btn-sm btn-primary" href=#></a></li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->

    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">All Years</h3>

                <div class="card-tools">
                  <div class="input-group input-group-sm" style="width: 150px;">
                    <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                    <div class="input-group-append">
                      <button type="submit" class="btn btn-default">
                        <i class="fas fa-search"></i>
                      </button>
                    </div>
                  </div>
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body table-responsive p-0" style="height: 300px;">
                <table class="table table-head-fixed text-nowrap">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>years</th>
                      <th>Terms</th>
                    </tr>
                  </thead>
                  <tbody>
                    {%for tarif in des %}
                    <tr>
                        <th scope="row">{{tarif.id}}</th>
                        <td>{{tarif.year__.name}}</td>     
                        <td><a href="{{url_for('extra.studentterms',id=tarif.year_id,stud=id)}}" class="nav-link">terms</a></td>               
                    </tr>
                    {%endfor%}
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        </div>
        </div>
</section>
  </div>
  <!-- /content-wrapper -->
  <footer class="main-footer">
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.1.0
    </div>
  </footer>

  <!-- /Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- /Control sidebar content goes here -->
  </aside>
  <!-- /control-sidebar -->
</div>
<!-- /wrapper -->

<!-- /jQuery -->
<script src="plugins/jquery/jquery.min.js"></script>
<!-- jQuery UI 1.11.4 -->
<script src="plugins/jquery-ui/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- ChartJS -->
<script src="plugins/chart.js/Chart.min.js"></script>
<!-- Sparkline -->
<script src="plugins/sparklines/sparkline.js"></script>
<!-- JQVMap -->
<script src="plugins/jqvmap/jquery.vmap.min.js"></script>
<script src="plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
<!-- jQuery Knob Chart -->
<script src="plugins/jquery-knob/jquery.knob.min.js"></script>
<!-- daterangepicker -->
<script src="plugins/moment/moment.min.js"></script>
<script src="plugins/daterangepicker/daterangepicker.js"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
<!-- Summernote -->
<script src="plugins/summernote/summernote-bs4.min.js"></script>
<!-- overlayScrollbars -->
<script src="plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
<!-- AdminLTE App -->
<script src="dist/js/adminlte.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="dist/js/demo.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="dist/js/pages/dashboard.js"></script>
</body>
</html>